### ISSUE TITLE
Default `npm run` doesn't work

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge-file-server#67]
### Current Behavior

The default config file in this repo contains:

https://github.com/flowforge/flowforge-file-server/blob/cca8027cf81f44a4c97b1bcc1b6eed28c7cdb936/etc/flowforge-storage.yml#L18-L19

However this is not valid as there is no `memory` context driver.

I had to change it to:
```
context:
  type: sequelize
  options:
    type: sqlite
    storage: ff-context.db
```

### Expected Behavior

To be able to run the default config without error

### Steps To Reproduce

1. clone
2. `npm install`
3. `npm run`

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:
